name: Build and Deploy to Elitehost

on:
  push:
    branches: [main] # change to your deployment branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18" # or your required version

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload to server via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.4.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist
          server-dir: ${{ secrets.FTP_REMOTE_PATH }}
          protocol: ftp
