name: Build and Deploy to Elitehost (SFTP/FTP)

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./simple-hoc
        run: npm ci

      - name: Build production
        working-directory: ./simple-hoc
        run: npm run build

      - name: Upload dist via FTP/SFTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          local-dir: ./simple-hoc/dist
          server-dir: ${{ secrets.FTP_REMOTE_PATH }}
